name: Deploy to Heroku Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BASE_URL: https://chattun-hackathon.herokuapp.com
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      # server deploy
      - run: cd chattun && git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git master
